apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: boardom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardom-backend
  template:
    metadata:
      labels:
        app: boardom-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/Mercantec-GHC/h3-boardom-backend-h3-eux:latest
          ports:
            - containerPort: 8080
